project:
  type: book

engine: knitr
book:
  version: 2025.09.03
  google-analytics: "G-9D75EFV0TE"
  title: "Applied HPC with R"
  author: "George G. Vega Yon"
  language: en
  repo-url: https://github.com/gvegayon/appliedhpcr
  repo-branch: master
  issue-url: https://github.com/gvegayon/appliedhpcr/issues
  repo-actions: [edit, source, issue]
  cover-image: 'fig/cover.png'
  cover-image-alt: 'Cover image for Applied HPC with R'
  description: 'This book is a collection of talks and lectures on how to speed up your R code using parallel computing and other resources like C++.'
  original-date: 2023-04-09
  date: 2025-09-04
  chapters:
    - index.qmd
    - part: "Fundamentals"
      chapters:
      - profiling.qmd
      - efficiency.qmd
    - part: "Parallel computing"
      chapters:
      - intro.qmd
      - parallel-pkg.qmd
    - part: "Working with a Cluster"
      chapters:
        - slurm-fundamentals.qmd
        - slurm-simpi.qmd
    - part: "Using C++"
      chapters:
        - rcpp-part1.qmd
        - rcpp-debugging.qmd
  appendices: 
    - misc.qmd
    - references.qmd
    - news.qmd
  downloads:
    - pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



