project:
  type: book

book:
  title: "Applied HPC with R"
  author: "George G. Vega Yon"
  date: "4/9/2023"
  chapters:
    - index.qmd
    - part: "Parallel computing"
      chapters:
      - intro.qmd
      - parallel-pkg.qmd
    - part: "Working with a Cluster"
      chapters:
        - slurm-fundamentals.qmd
        - slurm-simpi.qmd
    - part: "Using C++"
      chapters:
        - rcpp-part1.qmd
    - misc.qmd
    - references.qmd
  downloads:
    - epub
    - pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



