# Preface {.unnumbered}

The R programming language [@R] can be fantastic for most daily tasks. But as soon as you start dealing with more complicated problems, you may face the for-loop bottle-neck. If you ever encounter such a problem, this book is for you. Applied HPC with R is a collection of talks and lectures I have given about speeding up your R code using parallel computing and other resources such as C++. The contents have been primarily developed during my time at USC and UofU.[^thanksto]

[^thanksto]: With many to thank, including [Paul Marjoram](https://keck.usc.edu/faculty-search/paul-marjoram/), [Zhi Yang](https://zhiyang.netlify.app/){target="_blank"}, [Emil Hvitfeldt](https://www.emilhvitfeldt.com/){target="_blank"}, [Malcolm Barrett](https://malco.io/){target="_blank"}, [Garrett Weaver](https://www.linkedin.com/in/gmwusc/){target="_blank"}, [USC's IMAGE P01 research group](https://p01.uscbiostatistics.org/){target="_target"}, and my students both at USC and UoU.

The book was written using [quarto](https://quarto.org){target="_blank"} and is hosted on [GitHub](https://github.com/gvegayon/appliedhpcr){target="_blank"}, where you can access all the source code.

## About the Author

I am a Research Assistant Professor at the <a href="https://medicine.utah.edu/internal-medicine/epidemiology" target="_blank">**University of Utah's Division of Epidemiology**</a>, where I work on studying Complex Systems using Statistical Computing. I was born and raised in Chile. I have over ten years of experience <a href="https://github.com/gvegayon" target="_blank">developing scientific software</a> focusing on high-performance computing, data visualization, and social network analysis. My training is in Public Policy (M.A. <a href="https://uai.cl" target="_blank">UAI</a>, 2011), Economics (M.Sc. <a href="https://caltech.edu" target="_blank">Caltech</a>, 2015), and Biostatistics (Ph.D. <a href="https://usc.edu" target="_blank">USC</a>, 2020).

I obtained my Ph.D. in Biostatistics under the supervision of <a href="https://scholar.google.com/citations?user=Zj5ky5gAAAAJ&hl=en" target="_blank">**Prof. Paul Marjoram**</a> and <a href="https://kayladelahaye.net/" target="_blank">**Prof. Kayla de la Haye**</a>, with my dissertation titled "*Essays on Bioinformatics and Social Network Analysis: Statistical and Computational Methods for Complex Systems.*"

If you'd like to learn more about me, please visit my website at <a href="https://ggvy.cl" target="_blank">https://ggvy.cl</a>.

## AI Disclosure

Starting in mid-2023, I have been using AI to help me write this book. Mainly, I use a combination of [GitHub co-pilot](https://github.com/features/copilot){target="_blank"}, which aids with code and text. AI's role has been to help me write faster and more accurately, but it has not been involved in the book's conceptualization or the development of the methods presented here.

## About the cover

The cover image was created using ChatGPT/Dall-E version 5 using the prompt "I need you to draw a picture representing high-performance computing using the R programming language (which is mostly used for statistics). The picture will go as the cover of the book "Applied HPC with R". It should feature components related to C++, parallel computing, and high-performance computing"