FROM ghcr.io/rocker-org/devcontainer/tidyverse:4.5

# Installing quarto
RUN quarto install tool tinytex --log-level warning

ENV PATH="/root/.TinyTeX/bin/x86_64-linux:${PATH}"

RUN install2.r --error languageserver && \
    installGithub.r nx10/httpgd

# Installing needed packages
RUN install2.r --error microbenchmark slurmR future Rcpp RcppArmadillo \
    quarto lobstr

RUN apt-get update && \
    apt-get install vim valgrind -y --no-install-recommends

# Installing jupyter
RUN python3 -m pip install jupyter --break-system-packages

CMD ["bash"]
